print('Hello World')
# nome = input('Digite o seu nome:')
# print(nome)
number = eval(input('Digite a sua idade:'))
print('voce nasceu em {}'.format(2023 - number))
print(f'voce nasceu em {2023 - number}')
